name: flex_travel_sim
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  # login_firebase: ^0.0.5

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  go_router: ^14.6.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  pinput: ^4.0.0
  easy_localization: ^3.0.7+1
  flutter_stripe: ^11.5.0
  flutter_stripe_web: ^6.5.1
  url_launcher: ^6.3.2
  fluttertoast: ^8.2.12
  country_flags: ^3.3.0
  web: ^1.1.1
  qr_flutter: ^4.1.0
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  mocktail: ^1.0.0
  bloc_test: ^9.1.7
  get_it: ^7.7.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/icons/figma112/
    - assets/icons/figma141/
    - assets/icons/figma142/
    - assets/icons/figma143/
    - assets/icons/figma149/
    - assets/translations/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue_Roman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeue_Medium.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeue_Bold.otf
          weight: 700

flutter_gen:
  output: lib/gen
  line_length: 80

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter

  integrations:
    flutter_svg: true

  fonts:
    enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/main_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/logo/splash.png"
  color_dark: "#000000"
  image_dark: "assets/logo/splash.png"
  android_12:
    image: "assets/logo/splash.png"
    icon_background_color: "#000000"
  fullscreen: false
  info_plist_files:
    - 'ios/Runner/Info.plist'
