name: flex_travel_sim
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  # login_firebase: ^0.0.5

  cupertino_icons: ^1.0.8
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/
    - assets/icons/figma112/ 
    - assets/icons/figma141/
    - assets/icons/figma142/
    - assets/icons/figma143/
    - assets/icons/figma149/     

flutter_gen:
  output: lib/gen
  line_length: 80

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter

  integrations:
    flutter_svg: true

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue_Roman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeue_Medium.otf
          weight: 500          
        - asset: assets/fonts/HelveticaNeue_Bold.otf
          weight: 700    
