name: flex_travel_sim
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  # login_firebase: ^0.0.5

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  go_router: ^14.6.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - .env  
    - assets/
    - assets/icons/
    - assets/icons/figma112/ 
    - assets/icons/figma141/
    - assets/icons/figma142/
    - assets/icons/figma143/
    - assets/icons/figma149/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue_Roman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeue_Medium.otf
          weight: 500          
        - asset: assets/fonts/HelveticaNeue_Bold.otf
          weight: 700     

flutter_gen:
  output: lib/gen
  line_length: 80

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter

  integrations:
    flutter_svg: true

  fonts:
    enabled: true    
